CREATE TABLE SAI_FDB (mac_address varchar(100), bv_id uint64, IS_STATIC bool, BRIDGE_PORT_ID uint64, PACKET_ACTION varchar(10), FDB_METADATA int, PRIMARY KEY(mac_address, bv_id));
CREATE TABLE SAI_VLAN (vlan_id int, STP_INSTANCE int, MAX_LEARN_LIMIT int, DISABLE_LEARN bool, VLAN_METADATA int, PRIMARY KEY(vlan_id));
CREATE TABLE SAI_VLAN_PORT_LIST (vlan_id int, BRIDGE_PORT_ID uint64, TAGGING_MODE varchar(20), PRIMARY KEY(vlan_id, BRIDGE_PORT_ID),
FOREIGN KEY(vlan_id) REFERENCES SAI_VLAN(vlan_id) ON DELETE CASCADE);

PRAGMA foreign_keys = ON;
