DROP TABLE IF EXISTS "SAI_SWITCH_PORT_DFLT_INFO_TABLE";
DROP TABLE IF EXISTS "SAI_SWITCH_L2_DFLT_INFO_TABLE";
DROP TABLE IF EXISTS "SAI_SWITCH_L3_DFLT_INFO_TABLE";
DROP TABLE IF EXISTS "SAI_SWITCH_ACL_DFLT_INFO_TABLE";
DROP TABLE IF EXISTS "SAI_SWITCH_MISC_INFO_TABLE";
DROP TABLE IF EXISTS "SAI_SWITCH_L2_PARAMS_TABLE";
DROP TABLE IF EXISTS "SAI_SWITCH_FDB_PARAMS_TABLE";
