DROP TABLE IF EXISTS "SAI_ACL_COUNTER";
DROP TABLE IF EXISTS "SAI_ACL_ENTRY_ACTION_LIST";
DROP TABLE IF EXISTS "SAI_ACL_ENTRY_FILTER_LIST";
DROP TABLE IF EXISTS "SAI_ACL_ENTRY";
DROP TABLE IF EXISTS "SAI_ACL_TABLE_QUALIFIER_LIST";
DROP TABLE IF EXISTS "SAI_ACL_TABLE";
