DROP TABLE IF EXISTS "SAI_NEIGHBOR";
DROP TABLE IF EXISTS "SAI_NEXT_HOP_GROUP_LIST";
DROP TABLE IF EXISTS "SAI_NEXT_HOP_GROUP";
DROP TABLE IF EXISTS "SAI_ROUTE";
DROP TABLE IF EXISTS "SAI_ROUTER";
DROP TABLE IF EXISTS "SAI_ROUTER_INTF";
DROP TABLE IF EXISTS "SAI_NEIGHBOUR";
DROP TABLE IF EXISTS "SAI_NEXT_HOP";

